#!/bin/sh
#SBATCH -p clusterb
#SBATCH --ntasks 1200
#SBATCH --nodes  25
#SBATCH -J ufs_era5_replay
#SBATCH -e ufs_era5_replay.err
#SBATCH -o ufs_era5_replay.out
export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
echo NODES=$NODES
echo corespernode=$corespernode
export machine='aws'

# for control forecast
if [ $NODES -eq 25 ]; then # 0.25 degree setup
  export gsi_control_thread=2
  export control_threads=1
  export control_proc=1200 
  export write_groups=1 # write groups for control forecast.
  export write_tasks=48
  export layout="12,12" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=864
  export nprocs_atm=912
  export nprocs_ice=96
  export nprocs_ocn=144
  export nprocs_wav=48
else
  echo "processor layout for $NODES nodes not set"
  exit 1
fi

export gsi_control_threads=4
