#!/bin/sh
#SBATCH -t 01:30:00
##SBATCH --ntasks 684
##SBATCH --ntasks 720
##SBATCH --nodes  20
#SBATCH --ntasks 1332
##SBATCH --ntasks 1044
#SBATCH --nodes  37
#SBATCH -J ufs_era5_replay
#SBATCH -e ufs_era5_replay.err
#SBATCH -o ufs_era5_replay.out
export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
echo NODES=$NODES
echo corespernode=$corespernode
export machine='aws'

# for control forecast
if [ $NODES -eq 19 ]; then # 0.25 degree setup
  export gsi_control_thread=2
  export control_threads=1
  export control_proc=720  
  export write_groups=1 # write groups for control forecast.
  export write_tasks=36
  export layout="10,9" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=576
  export nprocs_atm=612
  export nprocs_ice=36
  export nprocs_ocn=36
elif [ $NODES -eq 20 ]; then # 0.25 degree setup
  export gsi_control_thread=2
  export control_threads=1
  export control_proc=720  
  export write_groups=1 # write groups for control forecast.
  export write_tasks=36
  export layout="12,8" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=576
  export nprocs_atm=612
  export nprocs_ice=36
  export nprocs_ocn=72
elif [ $NODES -eq 24 ]; then # 0.25 degree setup
  export gsi_control_thread=2
  export control_threads=1
  export control_proc=864  
  export write_groups=2 # write groups for control forecast.
  export write_tasks=36
  export layout="12,8" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=576
  export nprocs_atm=648
  export nprocs_ice=40
  export nprocs_ocn=128
elif [ $NODES -eq 29 ]; then # 0.25 degree setup
  export gsi_control_thread=2
  export control_threads=1
  export control_proc=1044 
  export write_groups=1 # write groups for control forecast.
  export write_tasks=36
  export layout="12,12" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=864
  export nprocs_atm=900
  export nprocs_ice=72
  export nprocs_ocn=72
elif [ $NODES -eq 30 ]; then # 0.25 degree setup
  export gsi_control_thread=2
  export control_threads=1
  export control_proc=1044 
  export write_groups=1 # write groups for control forecast.
  export write_tasks=36
  export layout="12,12" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=864
  export nprocs_atm=900
  export nprocs_ice=72
  export nprocs_ocn=72
elif [ $NODES -eq 31 ]; then # 0.25 degree setup
  export gsi_control_thread=2
  export control_threads=1
  export control_proc=1116 
  export write_groups=1 # write groups for control forecast.
  export write_tasks=36
  export layout="12,12" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=864
  export nprocs_atm=900
  export nprocs_ice=108
  export nprocs_ocn=108
elif [ $NODES -eq 33 ]; then # 0.25 degree setup
  export gsi_control_thread=2
  export control_threads=1
  export control_proc=1188 
  export write_groups=1 # write groups for control forecast.
  export write_tasks=36
  export layout="12,12" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=864
  export nprocs_atm=900
  export nprocs_ice=144
  export nprocs_ocn=144
elif [ $NODES -eq 37 ]; then # 0.25 degree setup
#  export gsi_control_thread=2
#  export control_threads=1
#  export control_proc=1332 
#  export write_groups=1 # write groups for control forecast.
#  export write_tasks=36
#  export layout="18,10" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
#  export nprocs_cpl=1080
#  export nprocs_atm=1116
#  export nprocs_ice=108
#  export nprocs_ocn=108
  export gsi_control_thread=2
  export control_threads=1
  export control_proc=1332 
  export write_groups=1 # write groups for control forecast.
  export write_tasks=36
  export layout="12,16" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=1152
  export nprocs_atm=1188
  export nprocs_ice=72 
  export nprocs_ocn=72
elif [ $NODES -eq 40 ]; then # 0.25 degree setup
  export gsi_control_thread=4
  export control_threads=1
  export control_proc=1440
  export write_groups=1 # write groups for control forecast.
  export write_tasks=36
  export layout="18,10" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=1080
  export nprocs_atm=1116
  export nprocs_ice=144
  export nprocs_ocn=180
else
  echo "processor layout for $NODES nodes not set"
  exit 1
fi

export gsi_control_threads=4
