#!/bin/sh
#SBATCH -t 01:30:00
#SBATCH -p clusterd
#SBATCH --ntasks 1280
#SBATCH --nodes  20
#SBATCH -J ufs_era5_replay
#SBATCH -e ufs_era5_replay.err
#SBATCH -o ufs_era5_replay.out
export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
echo NODES=$NODES
echo corespernode=$corespernode
export machine='aws'

# for control forecast
if [ $NODES -eq nw20 ]; then # 0.25 degree setup
  export gsi_control_thread=2
  export control_threads=1
  export control_proc=720  
  export write_groups=1 # write groups for control forecast.
  export write_tasks=36
  export layout="12,16" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=1152
  export nprocs_atm=1188
  export nprocs_ice=36
  export nprocs_ocn=56
elif [ $NODES -eq 20 ]; then # 0.25 degree setup
  export gsi_control_thread=2
  export control_threads=1
  export control_proc=1280 
  export write_groups=1 # write groups for control forecast.
  export write_tasks=64
  export layout="12,12" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=864
  export nprocs_atm=928
  export nprocs_ice=64
  export nprocs_ocn=160
  export nprocs_wav=128
else
  echo "processor layout for $NODES nodes not set"
  exit 1
fi

export gsi_control_threads=4
