#!/bin/sh
#SBATCH -q urgent 
#SBATCH -t 03:00:00
#SBATCH -A nggps_psd
#SBATCH --clusters c4
#SBATCH -N 44 
#SBATCH -J ufs_era5_replay_longfcst
#SBATCH -e ufs_era5_replay_longfcst.err
#SBATCH -o ufs_era5_replay_longfcst.out
export NODES=$SLURM_NNODES
# c4 is 36 cores per node, c3 is 32
export corespernode=$SLURM_CPUS_ON_NODE
export machine='gaea'

# for control forecast
if [ $NODES -eq 2 ]; then
  export gsi_control_threads=1
  export control_threads=1
  export control_proc=72
  export write_groups=4 # write groups for control forecast.
  export write_tasks=1
  export layout="3,2" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=36
  export nprocs_atm=40
  export nprocs_ice=8 
  export nprocs_ocn=24
elif [ $NODES -eq 11 ]; then # 0.25 degree setup
  export gsi_control_threads=4
  export control_threads=1
  export control_proc=396
  export write_groups=4 # write groups for control forecast.
  export write_tasks=9
  export layout="6,6" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=216 # layout*6
  export nprocs_atm=252 # nprocs_cpl + write_tasks*write_groups
  export nprocs_ice=36
  export nprocs_ocn=108
elif [ $NODES -eq 22 ]; then # 0.25 degree setup
  export gsi_control_threads=4
  export control_threads=1
  export control_proc=792
  export write_groups=4 # write groups for control forecast.
  export write_tasks=9
  export layout="12,6" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=432 # layout*6
  export nprocs_atm=468 # nprocs_cpl + write_tasks*write_groups
  export nprocs_ice=72
  export nprocs_ocn=252
elif [ $NODES -eq 44 ]; then # 0.25 degree setup
  export gsi_control_threads=6
  export control_threads=1
  export control_proc=1584
  export write_groups=4
  export write_tasks=18
  export layout="12,16" 
  export nprocs_cpl=1152 # layout*6
  export nprocs_atm=1224 # nprocs_cpl + write_tasks*write_groups
  export nprocs_ice=72   
  export nprocs_ocn=288
elif [ $NODES -eq 75 ]; then # 0.25 degree setup
  export gsi_control_threads=9
  export control_threads=1
  export control_proc=2700 # total processors used including threads
  export write_groups=4
  export write_tasks=18
  export layout="20,18" 
  export nprocs_cpl=2160 # layout*6
  export nprocs_atm=2232 # nprocs_cpl + write_tasks*write_groups
  export nprocs_ice=108  
  export nprocs_ocn=360
elif [ $NODES -eq 88 ]; then # 0.25 degree setup
  export gsi_control_threads=12
# export control_threads=2
# export control_proc=3168 # total processors used including threads
# export write_groups=4
# export write_tasks=18
# export layout="12,16" 
# export nprocs_cpl=1152 # layout*6
# export nprocs_atm=1224 # nprocs_cpl + write_tasks*write_groups
# export nprocs_ice=72   
# export nprocs_ocn=288
  export control_threads=1
  export control_proc=3168 # total processors used including threads
  export write_groups=4
  export write_tasks=36
  export layout="24,16" 
  export nprocs_cpl=2304 # layout*6
  export nprocs_atm=2448 # nprocs_cpl + write_tasks*write_groups
  export nprocs_ice=144  
  export nprocs_ocn=576
else
  echo "processor layout for $NODES nodes not set"
  exit 1
fi

