#!/bin/sh
#SBATCH -q debug
#SBATCH -t 00:30:00
##SBATCH -q batch
##SBATCH -t 01:30:00
#SBATCH -A gsienkf
#SBATCH -N 31   
#SBATCH -J ufs_era5_replay
#SBATCH -e ufs_era5_replay.err
#SBATCH -o ufs_era5_replay.out
export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
export machine='hera'

if [ $NODES -eq 16 ]; then
  export gsi_control_threads=2
  export control_threads=1
  export control_proc=840  
  export write_groups=1 # write groups for control forecast.
  export write_tasks=96
  export layout="8,8" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=384
  export nprocs_atm=480
  export nprocs_ice=40
  export nprocs_ocn=80
  export nprocs_wav=40
elif [ $NODES -eq 31 ]; then
  export gsi_control_threads=4
  export control_threads=1
  export control_proc=1240
  export write_groups=1 # write groups for control forecast.
  export write_tasks=96
  export layout="12,12" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
  export nprocs_cpl=864
  export nprocs_atm=960
  export nprocs_ice=80
  export nprocs_ocn=160 
  export nprocs_wav=40
else
  echo "processor layout for $NODES nodes not set"
  exit 1
fi
