#!/bin/sh
##SBATCH -q debug
##SBATCH -t 00:30:00
#SBATCH -q batch
#SBATCH -t 01:00:00
#SBATCH -A gsienkf
#SBATCH -N 17   
#SBATCH -J ufs_era5_replay_atm
#SBATCH -e ufs_era5_replay_atm.err
#SBATCH -o ufs_era5_replay_atm.out

export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
export machine='hera'

# for control forecast
if [ $NODES -eq 17 ]; then
  export gsi_control_threads=4
  export control_threads=1
  export control_proc=680  
  export write_groups=1 # write groups for control forecast.
  export write_tasks=80
  export layout="10,10" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
else
  echo "processor layout for $NODES nodes not set"
  exit 1
fi
